server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: blog-gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8082
          predicates:
            - Path=/api/auth/**
        - id: posts
          uri: http://localhost:8081
          predicates:
            - Path=/api/posts,/api/posts/**
        - id: friend-links
          uri: http://localhost:8081
          predicates:
            - Path=/api/friend-links/**
        - id: home-banners
          uri: http://localhost:8081
          predicates:
            - Path=/api/home-banners/**
        - id: uploads
          uri: http://localhost:8081
          predicates:
            - Path=/uploads/**

logging:
  level:
    root: info
    org.springframework.cloud.gateway: debug
